{% set name = "nomad-camels-driver-keithley-2400" %}
{% set version = "0.1.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nomad_camels_driver_keithley_2400-{{ version }}.tar.gz
  sha256: 9a1e3f42b15cecdc2047f1adbdbb3b00101aa7e846859b29fae03a713ae0011c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - nomad-camels >=0.2

test:
  requires:
    - python {{ python_min }}
  imports:
    - nomad_camels_driver_keithley_2400

about:
  home: https://github.com/FAU-LAP/CAMELS_drivers
  summary: Device driver for the Keithley 2400 source measure unit.
  license: LGPL-2.1-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
